In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport
import seaborn as sns
from datetime import datetime
import matplotlib.pyplot as plt

In [7]:
#rutas
ruta_dataset_finales =''
ruta_dataset_profile =''
ruta_dataset_splitting = ''
ruta_dataset_feature_creation = ''
ruta_dataset_discretizacion = ''

In [8]:
#para gráficos
sns.set_theme()
sns.set_style({"xtick.bottom": True, "ytick.left": True})
paleta=['#081d58','#253494','#225ea8','#1d91c0','#41b6c4','#7fcdbb','#c7e9b4','#edf8b1','#ffffd9']
paleta1=['#225ea8']
paleta2=['#225ea8','#41b6c4']

## Procesos

In [ ]:
data_procesos=pd.read_csv(ruta_dataset_feature_creation+"procesos2016_2022_nuevas_var.csv", sep='|', encoding='utf-8-sig')

In [10]:
data_procesos

,num_proceso,Expediente,nombre_proceso,tipo_proceso,fecha_apertura,estado,unidad_ejecutora,servicio_administrativo_financiero,Unnamed: 0.1,etapa,...,TOT_SERV_PROFESIONAL,TOT_SERV_NOTICIAS,TOT_SERV_BASICOS,TOT_TAPICERIA,TOT_TRANSPORTE,TOT_PROD_DEPORTIVOS,TOT_VIDRIERIA,TOT_VIGILANCIA,P_monto_total_procesos,P_cant_proveedores
0,23-0009-LPR16,EX-2016-00697885- -APN-DPYS#SGP,Adquisición de elementos de electricidad,Licitación Privada,13/10/2016 13:02 Hrs.,Adjudicado,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,0.0,Única,...,0.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0,5.517478e+06,4.0
1,23-0010-LPR16,EX-2016-01031683- -APN-DPYS#SGP,Adquisición de elementos de plomería y cerraje...,Licitación Privada,13/09/2016 11:00 Hrs.,Desierto,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,1.0,Única,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,23-0011-LPR16,EX-2016-01358346- -APN-DDMYA#SGP,ADQUISICIÓN INSUMOS PARA BAÑOS,Licitación Privada,19/12/2016 12:30 Hrs.,Adjudicado,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,2.0,Única,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.434774e+06,1.0
3,23-0012-LPR16,EX-2016-01392005- -APN-DDMYA#SGP,"Servicio anual de mantenimiento, y controles m...",Licitación Privada,30/11/2016 16:31 Hrs.,Adjudicado,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,3.0,Única,...,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.498171e+06,1.0
4,23-0014-LPU16,EX-2016-00474707- -APN-DPYS#SGP,Adquisición de indumentaria.,Licitación Pública,27/10/2016 12:00 Hrs.,Adjudicado,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,4.0,Única,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.100068e+07,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69681,95-0189-CDI21,EX-2021-124397120- -APN-DCYC#MDS,CONTRATACIÓN DIRECTA CON UNA UNIVERSIDAD NACIO...,Contratación Directa,18/01/2022 10:00 Hrs.,Desierto,95/000 - Dirección General de Administración -...,311 - Ministerio de Desarrollo Social,12.0,Única,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
69682,96-0054-CDI22,EX-2022-44338308- -APN-DC#HP,"ADQUISICIÓN DE ÁCIDO 2,3 - DIMERCAPTOSUCCÍNICO...",Contratación Directa,21/06/2022 13:00 Hrs.,Desierto,96 - Dirección General de Administración,908 - Hospital Nacional Profesor Alejandro Pos...,33.0,Única,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
69683,96-0118-CDI22,EX-2022-121335498- -APN-DC#HP,CALIBRACIÓN DE EQUIPAMIENTO Y ELEMENTOS DE MED...,Contratación Directa,23/11/2022 13:00 Hrs.,Desierto,96 - Dirección General de Administración,908 - Hospital Nacional Profesor Alejandro Pos...,42.0,Única,...,51.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
69684,98-0012-CDI22,EX-2022-44810023- -APN-DA#FMLCAV,ADQUISICIÓN DE VACUNAS ANTIGRIPALES,Contratación Directa,16/05/2022 11:00 Hrs.,Desierto,98/00 - Dir. Compras,101 - Fundación Miguel Lillo,36.0,Única,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
69685,98-0027-CDI22,EX-2022-108159624- -APN-DA#FMLCAV,SERVICIO DE CAMBIO DE ALFOMBRA EN EL CENTRO CU...,Contratación Directa,04/11/2022 11:00 Hrs.,Desierto,98/00 - Dir. Compras,101 - Fundación Miguel Lillo,43.0,Única,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [62]:
#se elimina columna
data_procesos=data_procesos.drop(['Unnamed: 0.1'], axis=1)

#### discretización de proveedores participantes

In [11]:
#se discretiza la variable proveedores participantes y para ello se construyen veintiles 
data_procesos['d_proveedores_participantes'] = pd.qcut(data_procesos['proveedores_participantes'], q=20,duplicates='drop')
data_procesos['d_proveedores_participantes'].describe()

count             69686
unique               12
top       (-0.001, 1.0]
freq              20912
Name: d_proveedores_participantes, dtype: object

In [12]:
datos=data_procesos.groupby(['d_proveedores_participantes']).size().reset_index(name='Nro procesos')
datos['total']=data_procesos['d_proveedores_participantes'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_19292\1985154109.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_procesos.groupby(['d_proveedores_participantes']).size().reset_index(name='Nro procesos')

   d_proveedores_participantes  Nro procesos  total
0                (-0.001, 1.0]         20912  69686
1                   (1.0, 2.0]          8052  69686
2                   (2.0, 3.0]          6995  69686
3                   (3.0, 4.0]          5894  69686
4                   (4.0, 5.0]          4993  69686
5                   (5.0, 6.0]          4245  69686
6                   (6.0, 7.0]          3391  69686
7                   (7.0, 8.0]          2845  69686
8                   (8.0, 9.0]          2308  69686
9                  (9.0, 11.0]          3355  69686
10                (11.0, 15.0]          3656  69686
11               (15.0, 319.0]          3040  69686

#### discretización de ofertas confirmadas

In [13]:
data_procesos['d_ofertas_confirmadas'] = pd.qcut(data_procesos['ofertas_confirmadas'], q=20,duplicates='drop')
#pd.qcut(s,len(s.dropna()),duplicates='drop')
data_procesos['d_ofertas_confirmadas'].describe()

count             69686
unique                9
top       (-0.001, 1.0]
freq              28458
Name: d_ofertas_confirmadas, dtype: object

In [14]:
datos=data_procesos.groupby(['d_ofertas_confirmadas']).size().reset_index(name='Nro procesos')
datos['total']=data_procesos['d_ofertas_confirmadas'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_19292\1377542942.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_procesos.groupby(['d_ofertas_confirmadas']).size().reset_index(name='Nro procesos')

  d_ofertas_confirmadas  Nro procesos  total
0         (-0.001, 1.0]         28458  69686
1            (1.0, 2.0]         10032  69686
2            (2.0, 3.0]          7694  69686
3            (3.0, 4.0]          5764  69686
4            (4.0, 5.0]          4434  69686
5            (5.0, 6.0]          3336  69686
6            (6.0, 8.0]          4373  69686
7           (8.0, 10.0]          2346  69686
8         (10.0, 105.0]          3249  69686

#### discretización de días de recepción de documentos en soporte físico

In [15]:
data_procesos['dias_recepción_doc_soporte_fisico']=data_procesos['dias_recepción_doc_soporte_fisico'].replace('sin datos', np.nan)
data_procesos['dias_recepción_doc_soporte_fisico']=pd.to_numeric(data_procesos['dias_recepción_doc_soporte_fisico'])
data_procesos['d_dias_recepcion_doc_soporte_fisico'] = pd.qcut(data_procesos['dias_recepción_doc_soporte_fisico'], q=20,duplicates='drop')
#pd.qcut(s,len(s.dropna()),duplicates='drop')
data_procesos['d_dias_recepcion_doc_soporte_fisico'].describe()

count          30094
unique            16
top       (6.0, 7.0]
freq            3429
Name: d_dias_recepcion_doc_soporte_fisico, dtype: object

#### discretización de cantidad total de bienes

In [16]:
data_procesos['d_cant_total_bienes'] = pd.qcut(data_procesos['cant_total_bienes'], q=20,duplicates='drop')
#pd.qcut(s,len(s.dropna()),duplicates='drop')
data_procesos['d_cant_total_bienes'].describe()

count             69266
unique               12
top       (-0.001, 1.0]
freq              31643
Name: d_cant_total_bienes, dtype: object

In [17]:
datos=data_procesos.groupby(['d_cant_total_bienes']).size().reset_index(name='Nro procesos')
datos['total']=data_procesos['d_cant_total_bienes'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_19292\2570816255.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_procesos.groupby(['d_cant_total_bienes']).size().reset_index(name='Nro procesos')

       d_cant_total_bienes  Nro procesos  total
0            (-0.001, 1.0]         31643  69266
1               (1.0, 5.0]          3247  69266
2              (5.0, 16.0]          3233  69266
3             (16.0, 45.0]          3519  69266
4            (45.0, 102.0]          3405  69266
5           (102.0, 230.0]          3451  69266
6          (230.0, 493.75]          3451  69266
7         (493.75, 1003.0]          3469  69266
8        (1003.0, 2163.25]          3458  69266
9        (2163.25, 5833.0]          3463  69266
10       (5833.0, 26197.5]          3463  69266
11  (26197.5, 650697097.0]          3464  69266

#### discretización de cantidad total de servicios

In [18]:
data_procesos['d_cant_total_servicios'] = pd.qcut(data_procesos['cant_total_servicios'], q=20,duplicates='drop')
data_procesos['d_cant_total_servicios'].describe()

count             69266
unique                7
top       (-0.001, 1.0]
freq              48613
Name: d_cant_total_servicios, dtype: object

In [19]:
datos=data_procesos.groupby(['d_cant_total_servicios']).size().reset_index(name='Nro procesos')
datos['total']=data_procesos['d_cant_total_servicios'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_19292\153909069.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_procesos.groupby(['d_cant_total_servicios']).size().reset_index(name='Nro procesos')

  d_cant_total_servicios  Nro procesos  total
0          (-0.001, 1.0]         48613  69266
1             (1.0, 4.0]          3511  69266
2            (4.0, 12.0]          6715  69266
3           (12.0, 13.0]           303  69266
4           (13.0, 36.0]          3311  69266
5          (36.0, 278.0]          3350  69266
6   (278.0, 275762175.0]          3463  69266

#### discretización de monto total de procesos

In [20]:
data_procesos['dP_monto_total_procesos'] = pd.qcut(data_procesos['P_monto_total_procesos'], q=20,duplicates='drop')
data_procesos['dP_monto_total_procesos'].describe()

count                   54125
unique                     20
top       (-0.001, 25566.546]
freq                     2707
Name: dP_monto_total_procesos, dtype: object

In [21]:
datos=data_procesos.groupby(['dP_monto_total_procesos']).size().reset_index(name='Nro procesos')
datos['total']=data_procesos['dP_monto_total_procesos'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_19292\3823659080.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_procesos.groupby(['dP_monto_total_procesos']).size().reset_index(name='Nro procesos')

          dP_monto_total_procesos  Nro procesos  total
0             (-0.001, 25566.546]          2707  54125
1           (25566.546, 65560.04]          2706  54125
2          (65560.04, 110307.844]          2706  54125
3        (110307.844, 167149.424]          2706  54125
4        (167149.424, 234308.571]          2707  54125
5          (234308.571, 317475.0]          2707  54125
6          (317475.0, 420237.552]          2705  54125
7        (420237.552, 549445.963]          2706  54125
8        (549445.963, 712334.153]          2706  54125
9        (712334.153, 930952.381]          2707  54125
10      (930952.381, 1217909.697]          2706  54125
11     (1217909.697, 1623406.722]          2706  54125
12     (1623406.722, 2156277.455]          2706  54125
13     (2156277.455, 2950511.575]          2706  54125
14      (2950511.575, 4117933.29]          2707  54125
15      (4117933.29, 6112646.722]          2706  54125
16      (6112646.722, 9564554.25]          2706  54125
17     (9564554.25, 16889709.634]          2706  54125
18   (16889709.634, 41254081.713]          2706  54125
19  (41254081.713, 16438422000.0]          2707  54125

#### discretización de cantidad de proveedores

In [22]:
data_procesos['dP_cant_proveedores'] = pd.qcut(data_procesos['P_cant_proveedores'], q=20,duplicates='drop')
data_procesos['dP_cant_proveedores'].describe()

count            54125
unique               5
top       (0.999, 2.0]
freq             42786
Name: dP_cant_proveedores, dtype: object

In [23]:
datos=data_procesos.groupby(['dP_cant_proveedores']).size().reset_index(name='Nro procesos')
datos['total']=data_procesos['dP_cant_proveedores'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_19292\1409097728.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_procesos.groupby(['dP_cant_proveedores']).size().reset_index(name='Nro procesos')

  dP_cant_proveedores  Nro procesos  total
0        (0.999, 2.0]         42786  54125
1          (2.0, 3.0]          4118  54125
2          (3.0, 4.0]          2743  54125
3          (4.0, 6.0]          2658  54125
4         (6.0, 31.0]          1820  54125

#### discretización de duración de contrato en días

In [24]:
data_procesos['d_duracion_contrato_dias']=data_procesos['duracion_contrato_dias'].replace('sin datos', np.nan)
data_procesos['d_duracion_contrato_dias']=pd.to_numeric(data_procesos['duracion_contrato_dias'])
data_procesos['d_duracion_contrato_dias'] = pd.qcut(data_procesos['duracion_contrato_dias'], q=20,duplicates='drop')
#pd.qcut(s,len(s.dropna()),duplicates='drop')
data_procesos['d_duracion_contrato_dias'].describe()

count              69276
unique                15
top       (180.0, 360.0]
freq               19799
Name: d_duracion_contrato_dias, dtype: object

In [25]:
datos=data_procesos.groupby(['d_duracion_contrato_dias']).size().reset_index(name='Nro procesos')
datos['total']=data_procesos['d_duracion_contrato_dias'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_19292\2363356899.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_procesos.groupby(['d_duracion_contrato_dias']).size().reset_index(name='Nro procesos')

   d_duracion_contrato_dias  Nro procesos  total
0             (0.999, 14.0]          6249  69276
1              (14.0, 15.0]          3658  69276
2              (15.0, 20.0]          1401  69276
3              (20.0, 21.0]          5587  69276
4              (21.0, 28.0]          2068  69276
5              (28.0, 30.0]          4941  69276
6              (30.0, 40.0]           460  69276
7              (40.0, 42.0]          3408  69276
8              (42.0, 60.0]          4098  69276
9              (60.0, 90.0]          6176  69276
10             (90.0, 98.0]            96  69276
11            (98.0, 168.0]          3466  69276
12           (168.0, 180.0]          4888  69276
13           (180.0, 360.0]         19799  69276
14        (360.0, 364635.0]          2981  69276

In [26]:
data_procesos

,num_proceso,Expediente,nombre_proceso,tipo_proceso,fecha_apertura,estado,unidad_ejecutora,servicio_administrativo_financiero,Unnamed: 0.1,etapa,...,P_monto_total_procesos,P_cant_proveedores,d_proveedores_participantes,d_ofertas_confirmadas,d_dias_recepcion_doc_soporte_fisico,d_cant_total_bienes,d_cant_total_servicios,dP_monto_total_procesos,dP_cant_proveedores,d_duracion_contrato_dias
0,23-0009-LPR16,EX-2016-00697885- -APN-DPYS#SGP,Adquisición de elementos de electricidad,Licitación Privada,13/10/2016 13:02 Hrs.,Adjudicado,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,0.0,Única,...,5.517478e+06,4.0,"(8.0, 9.0]","(4.0, 5.0]","(15.0, 18.0]","(26197.5, 650697097.0]","(-0.001, 1.0]","(4117933.29, 6112646.722]","(3.0, 4.0]","(0.999, 14.0]"
1,23-0010-LPR16,EX-2016-01031683- -APN-DPYS#SGP,Adquisición de elementos de plomería y cerraje...,Licitación Privada,13/09/2016 11:00 Hrs.,Desierto,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,1.0,Única,...,NaN,NaN,"(1.0, 2.0]","(-0.001, 1.0]","(10.0, 11.0]","(5833.0, 26197.5]","(-0.001, 1.0]",NaN,NaN,"(28.0, 30.0]"
2,23-0011-LPR16,EX-2016-01358346- -APN-DDMYA#SGP,ADQUISICIÓN INSUMOS PARA BAÑOS,Licitación Privada,19/12/2016 12:30 Hrs.,Adjudicado,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,2.0,Única,...,5.434774e+06,1.0,"(7.0, 8.0]","(2.0, 3.0]","(6.0, 7.0]","(5833.0, 26197.5]","(-0.001, 1.0]","(4117933.29, 6112646.722]","(0.999, 2.0]","(180.0, 360.0]"
3,23-0012-LPR16,EX-2016-01392005- -APN-DDMYA#SGP,"Servicio anual de mantenimiento, y controles m...",Licitación Privada,30/11/2016 16:31 Hrs.,Adjudicado,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,3.0,Única,...,4.498171e+06,1.0,"(5.0, 6.0]","(4.0, 5.0]","(-0.001, 1.0]","(1003.0, 2163.25]","(13.0, 36.0]","(4117933.29, 6112646.722]","(0.999, 2.0]","(180.0, 360.0]"
4,23-0014-LPU16,EX-2016-00474707- -APN-DPYS#SGP,Adquisición de indumentaria.,Licitación Pública,27/10/2016 12:00 Hrs.,Adjudicado,23/000 - Dirección General de Administración - SG,301 - Secretaria General de la Presidencia de ...,4.0,Única,...,1.100068e+07,10.0,"(6.0, 7.0]","(5.0, 6.0]","(22.0, 383.0]","(2163.25, 5833.0]","(-0.001, 1.0]","(9564554.25, 16889709.634]","(6.0, 31.0]","(98.0, 168.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69681,95-0189-CDI21,EX-2021-124397120- -APN-DCYC#MDS,CONTRATACIÓN DIRECTA CON UNA UNIVERSIDAD NACIO...,Contratación Directa,18/01/2022 10:00 Hrs.,Desierto,95/000 - Dirección General de Administración -...,311 - Ministerio de Desarrollo Social,12.0,Única,...,NaN,NaN,"(-0.001, 1.0]","(-0.001, 1.0]",NaN,"(-0.001, 1.0]","(-0.001, 1.0]",NaN,NaN,"(180.0, 360.0]"
69682,96-0054-CDI22,EX-2022-44338308- -APN-DC#HP,"ADQUISICIÓN DE ÁCIDO 2,3 - DIMERCAPTOSUCCÍNICO...",Contratación Directa,21/06/2022 13:00 Hrs.,Desierto,96 - Dirección General de Administración,908 - Hospital Nacional Profesor Alejandro Pos...,33.0,Única,...,NaN,NaN,"(-0.001, 1.0]","(-0.001, 1.0]",NaN,"(102.0, 230.0]","(-0.001, 1.0]",NaN,NaN,"(168.0, 180.0]"
69683,96-0118-CDI22,EX-2022-121335498- -APN-DC#HP,CALIBRACIÓN DE EQUIPAMIENTO Y ELEMENTOS DE MED...,Contratación Directa,23/11/2022 13:00 Hrs.,Desierto,96 - Dirección General de Administración,908 - Hospital Nacional Profesor Alejandro Pos...,42.0,Única,...,NaN,NaN,"(-0.001, 1.0]","(-0.001, 1.0]",NaN,"(-0.001, 1.0]","(36.0, 278.0]",NaN,NaN,"(0.999, 14.0]"
69684,98-0012-CDI22,EX-2022-44810023- -APN-DA#FMLCAV,ADQUISICIÓN DE VACUNAS ANTIGRIPALES,Contratación Directa,16/05/2022 11:00 Hrs.,Desierto,98/00 - Dir. Compras,101 - Fundación Miguel Lillo,36.0,Única,...,NaN,NaN,"(-0.001, 1.0]","(-0.001, 1.0]",NaN,"(102.0, 230.0]","(-0.001, 1.0]",NaN,NaN,"(168.0, 180.0]"
69685,98-0027-CDI22,EX-2022-108159624- -APN-DA#FMLCAV,SERVICIO DE CAMBIO DE ALFOMBRA EN EL CENTRO CU...,Contratación Directa,04/11/2022 11:00 Hrs.,Desierto,98/00 - Dir. Compras,101 - Fundación Miguel Lillo,43.0,Única,...,NaN,NaN,"(-0.001, 1.0]","(-0.001, 1.0]",NaN,"(-0.001, 1.0]","(-0.001, 1.0]",NaN,NaN,"(40.0, 42.0]"

In [27]:
data_procesos.to_csv(ruta_dataset_discretizacion+"procesos2016_2022_nuevas_var_disc_ipc.csv", sep='|', encoding='utf-8-sig')

# Proveedores

In [4]:
data_proveedores=pd.read_csv(ruta_dataset_feature_creation+"proveedores2016_2022_nuevas_var.csv", sep='|', encoding='utf-8-sig')

In [9]:
prof = ProfileReport(data_proveedores, minimal=True)
prof.to_file(output_file=ruta_dataset_discretizacion+'Proveedores2022CompletoDiscretizado.html')

Summarize dataset:   0%|                                         | 0/87 [00:00<?, ?it/s, Describe variable: NumeroEnte]
Summarize dataset:  15%|████▋                          | 13/87 [00:01<00:08,  8.29it/s, Describe variable: cant_socios]
Summarize dataset:  39%|███████████▎                 | 34/87 [00:01<00:00, 55.27it/s, Describe variable: TOT_CONCESION]
Summarize dataset:  48%|█████████████▌              | 42/87 [00:02<00:00, 65.09it/s, Describe variable: TOT_FERRETERIA]
Summarize dataset:  63%|█████████████████▋          | 55/87 [00:02<00:00, 73.78it/s, Describe variable: TOT_METALURGIA]
Summarize dataset:  78%|█████████████████████▉      | 68/87 [00:02<00:00, 77.06it/s, Describe variable: TOT_TRANSPORTE]
Summarize dataset:  89%|███████████████  | 77/87 [00:02<00:00, 65.16it/s, Describe variable: dcant_procesos_adjudicado]
100%|██████████████████████████████████████████████████████████████████████████████████| 82/82 [00:02<00:00, 36.19it/s]
Summarize dataset: 100%|████████████████████████████████████████████████████| 88/88 [00:02<00:00, 35.44it/s, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████| 1/1 [00:42<00:00, 42.75s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.18s/it]
Export report to file: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.35it/s]

In [5]:
data_proveedores

,CUIT,Nombre,FechaPreinscripcion,Estado,TelefonicoContacto,Constitucion,TipoSocietario,NumeroEnte,DomicilioLegal,DomicilioEspecial,...,TOT_PLOMERIA,TOT_SERV_PROFESIONAL,TOT_SERV_NOTICIAS,TOT_SERV_BASICOS,TOT_TAPICERIA,TOT_TRANSPORTE,TOT_PROD_DEPORTIVOS,TOT_VIDRIERIA,TOT_VIGILANCIA,total_articulos_provee
0,27236909900,EMR VENTAS & SERVICIOS,04/10/2016,Inscripto,2804357488,sin datos,Persona Física,4335080,"CACIQUE FRANCISCO 1398, localidad TRELEW, depa...","CACIQUE FRANCISCO 1398, localidad TRELEW, depa...",...,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68.0
1,30569211685,Electricidad Chiclana de R. Santoianni y O.S. ...,18/08/2016,Desactualizado Por Documentos Vencidos,54114923-4922,En C.A.B.A. con fecha 28/05/1980,Sociedades De Hecho,36170,"Av. Boedo 1986, piso N° P.B., localidad Ciudad...","Av. Boedo 1986, piso N° P.B., localidad Ciudad...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,330.0
2,30711500363,LICICOM S.R.L.,15/09/2016,Inscripto,45833433,"En JUAN B JUSTO Nº 925, LANUS, PROV DE BS AS c...",Sociedad Responsabilidad Limitada,3893780,"AV CORRIENTES 4709, piso N° 3, depto N° 36, lo...","SAN BLAS 2257, piso N° PB, depto N° PB, locali...",...,63.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,105.0
3,30708415487,YLUM S.A.,24/08/2016,Inscripto,541149116641,"En Rodriguez Peña 694 5º D, CABA con fecha 28/...",Sociedad Anónima,2141900,"Rodriguez Peña 694, localidad Ciudad Autónoma ...","Famatina 3933, localidad Ciudad Autónoma de Bu...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,83.0
4,33712286089,COMPAÑÍA DE HIGIENE,26/10/2016,Inscripto,541147901907,En BUENOS AIRES con fecha 08/07/2011,Sociedad Responsabilidad Limitada,4715650,"O'Higgins 3550, localidad OLIVOS, departamento...","Obispo San Alberto 2975, localidad Ciudad Autó...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10071,20287286687,LAZARTE MARIO,03/08/2022,Inscripto,2235465989,sin datos,Persona Física,33330,"CARAZA 3530, localidad MAR DEL PLATA, departam...","CARAZA 3530, localidad MAR DEL PLATA, departam...",...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
10072,30518773743,Hotel Astor Sociedad Anonima Comercial,25/07/2022,Inscripto,541143222400,En Tigre con fecha 09/12/1968,Sociedad Anónima,16220,"Azcuenaga 1721, piso N° 6, depto N° G, localid...","Entre Rios 1649, localidad MAR DEL PLATA, depa...",...,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
10073,30700503891,GIJON SA,07/09/2022,Inscripto,1160190901,En CABA con fecha 23/07/1998,Sociedad Anónima,18500,"VERA PEÑALOZA,ROSARIO BOULEVARD 360, localidad...","VERA PEÑALOZA,ROSARIO BOULEVARD 360, localidad...",...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10074,30716441098,LISTOS PARA RODAR SAS,16/08/2019,Inscripto,1531111101,En BUENOS AIRES con fecha 01/04/2019,Otras Formas Societarias,67820,"CRAMER 40, piso N° 1, localidad Ciudad Autónom...","CRAMER 40, piso N° 1, localidad Ciudad Autónom...",...,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
10075,27331126530,sin datos,18/08/2022,Inscripto,1167418098,sin datos,Persona Física,80550,"Salcedo 3588, piso N° 1, depto N° C, localidad...","Salcedo 3588, piso N° 1, depto N° C, localidad...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

#Discretizar
cant_procesos_adjudicado
monto_total_adjudicado
antiguedad
cant_socios
cant_apercibimientos
cant_suspensiones
cant_antecedentes
cant_Apoderado
cant_representante
cant_autenticado
cant_noAutenticado
cant_sinMontoLimite
cant_MontoLimite
total_articulos_provee

#### discretización de monto total adjudicado

In [6]:
data_proveedores['dmonto_total_adjudicado'] = pd.qcut(data_proveedores['monto_total_adjudicado'], q=20,duplicates='drop')
data_proveedores['dmonto_total_adjudicado'].describe()

count                   10025
unique                     20
top       (-0.001, 33011.111]
freq                      502
Name: dmonto_total_adjudicado, dtype: object

#### discretización de cantidad de procesos adjudicados

In [7]:
data_proveedores['dcant_procesos_adjudicado'] = pd.qcut(data_proveedores['cant_procesos_adjudicado'], q=20,duplicates='drop')
data_proveedores['dcant_procesos_adjudicado'].describe()

count            10025
unique              10
top       (0.999, 2.0]
freq              5446
Name: dcant_procesos_adjudicado, dtype: object

In [8]:
datos=data_proveedores.groupby(['dcant_procesos_adjudicado']).size().reset_index(name='Nro procesos')
datos['total']=data_proveedores['dcant_procesos_adjudicado'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_8860\3713433172.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_proveedores.groupby(['dcant_procesos_adjudicado']).size().reset_index(name='Nro procesos')

  dcant_procesos_adjudicado  Nro procesos  total
0              (0.999, 2.0]          5446  10025
1                (2.0, 3.0]           933  10025
2                (3.0, 4.0]           594  10025
3                (4.0, 5.0]           364  10025
4                (5.0, 6.0]           330  10025
5                (6.0, 8.0]           391  10025
6               (8.0, 12.0]           530  10025
7              (12.0, 19.0]           452  10025
8              (19.0, 39.0]           489  10025
9            (39.0, 1214.0]           496  10025

In [30]:
datos=data_proveedores.groupby(['dmonto_total_adjudicado']).size().reset_index(name='Nro procesos')
datos['total']=data_proveedores['dmonto_total_adjudicado'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_16784\1994602942.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_proveedores.groupby(['dmonto_total_adjudicado']).size().reset_index(name='Nro procesos')

          dmonto_total_adjudicado  Nro procesos  total
0             (-0.001, 33011.111]           502  10025
1         (33011.111, 104767.373]           501  10025
2        (104767.373, 224078.198]           501  10025
3        (224078.198, 377939.298]           501  10025
4          (377939.298, 599760.0]           502  10025
5            (599760.0, 890758.9]           501  10025
6         (890758.9, 1302657.558]           501  10025
7      (1302657.558, 1793326.755]           501  10025
8      (1793326.755, 2483085.385]           501  10025
9        (2483085.385, 3396600.0]           502  10025
10       (3396600.0, 4727330.113]           501  10025
11     (4727330.113, 6702697.888]           501  10025
12     (6702697.888, 9424898.401]           501  10025
13     (9424898.401, 13557176.81]           501  10025
14     (13557176.81, 19975532.58]           502  10025
15     (19975532.58, 30451916.51]           501  10025
16    (30451916.51, 46718747.516]           501  10025
17   (46718747.516, 89439449.702]           501  10025
18   (89439449.702, 222964579.98]           501  10025
19  (222964579.98, 46172150151.0]           502  10025

In [9]:
datos=data_proveedores.groupby(['dmonto_total_adjudicado']).size().reset_index(name='Nro procesos')
datos['total']=data_proveedores['dmonto_total_adjudicado'].count()
datos

          dmonto_total_adjudicado  Nro procesos  total
0             (-0.001, 33011.111]           502  10025
1         (33011.111, 104767.373]           501  10025
2        (104767.373, 224078.198]           501  10025
3        (224078.198, 377939.298]           501  10025
4          (377939.298, 599760.0]           502  10025
5            (599760.0, 890758.9]           501  10025
6         (890758.9, 1302657.558]           501  10025
7      (1302657.558, 1793326.755]           501  10025
8      (1793326.755, 2483085.385]           501  10025
9        (2483085.385, 3396600.0]           502  10025
10       (3396600.0, 4727330.113]           501  10025
11     (4727330.113, 6702697.888]           501  10025
12     (6702697.888, 9424898.401]           501  10025
13     (9424898.401, 13557176.81]           501  10025
14     (13557176.81, 19975532.58]           502  10025
15     (19975532.58, 30451916.51]           501  10025
16    (30451916.51, 46718747.516]           501  10025
17   (46718747.516, 89439449.702]           501  10025
18   (89439449.702, 222964579.98]           501  10025
19  (222964579.98, 46172150151.0]           502  10025

In [69]:
#antiguedad
#data_proveedores['dantiguedad'] = pd.qcut(data_proveedores['antiguedad'], q=20,duplicates='drop')
#data_proveedores['dantiguedad'].describe()

count           9977
unique             5
top       (3.0, 4.0]
freq            3662
Name: dantiguedad, dtype: object

In [70]:
#datos=data_proveedores.groupby(['dantiguedad']).size().reset_index(name='Nro procesos')
#datos['total']=data_proveedores['dantiguedad'].count()
#datos

     dantiguedad  Nro procesos  total
0  (-0.001, 1.0]          2045   9977
1     (1.0, 2.0]           993   9977
2     (2.0, 3.0]          1736   9977
3     (3.0, 4.0]          3662   9977
4     (4.0, 5.0]          1541   9977

In [72]:
#No tiene sentido esta variable porque no reduce dimensiones, así que se elimina del dataset
data_proveedores=data_proveedores.drop('dantiguedad', inplace=True, axis=1)

In [82]:
print(data_proveedores['total_articulos_provee'].dtype)
#print(df['nombre_de_la_columna'].dtype)

float64

In [31]:
#total_articulos_provee

data_proveedores['dtotal_articulos_provee'] = pd.qcut(data_proveedores['total_articulos_provee'], q=20,duplicates='drop')
data_proveedores['dtotal_articulos_provee'].describe()

count             9977
unique              15
top       (0.999, 2.0]
freq              3107
Name: dtotal_articulos_provee, dtype: object

In [32]:
datos=data_proveedores.groupby(['dtotal_articulos_provee']).size().reset_index(name='Nro procesos')
datos['total']=data_proveedores['dtotal_articulos_provee'].count()
datos

C:\Users\Vanina\AppData\Local\Temp\ipykernel_16784\4101868244.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  datos=data_proveedores.groupby(['dtotal_articulos_provee']).size().reset_index(name='Nro procesos')

   dtotal_articulos_provee  Nro procesos  total
0             (0.999, 2.0]          3107   9977
1               (2.0, 3.0]           500   9977
2               (3.0, 4.0]           404   9977
3               (4.0, 6.0]           627   9977
4               (6.0, 8.0]           441   9977
5              (8.0, 11.0]           489   9977
6             (11.0, 15.0]           480   9977
7             (15.0, 21.0]           504   9977
8             (21.0, 29.0]           461   9977
9             (29.0, 40.0]           485   9977
10            (40.0, 58.0]           486   9977
11            (58.0, 97.6]           496   9977
12           (97.6, 161.0]           500   9977
13          (161.0, 345.0]           499   9977
14         (345.0, 6993.0]           498   9977

In [33]:
#save de new dataset
data_proveedores.to_csv(ruta_dataset_discretizacion+"proveedores2016_2022_nuevas_var_disc_ipc.csv", sep='|', encoding='utf-8-sig')